// <auto-generated />
using System;
using FastFoodApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215161344_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastFoodApp.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440012"),
                            Name = "Salads"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440013"),
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440050"),
                            Address = "123 Main Street, Apt 4B",
                            City = "New York",
                            Phone = "+1-555-0100",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440030"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Description = "Classic pizza with tomato sauce, mozzarella, and basil",
                            ImageUrl = "https://example.com/margherita.jpg",
                            IsAvailable = true,
                            Name = "Margherita Pizza",
                            Price = 12.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440020")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440031"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Description = "Pizza with tomato sauce, mozzarella, and pepperoni",
                            ImageUrl = "https://example.com/pepperoni.jpg",
                            IsAvailable = true,
                            Name = "Pepperoni Pizza",
                            Price = 14.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440020")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440032"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Description = "Juicy burger with beef patty, lettuce, tomato, and special sauce",
                            ImageUrl = "https://example.com/burger.jpg",
                            IsAvailable = true,
                            Name = "Classic Burger",
                            Price = 9.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440021")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440033"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Description = "Burger with beef patty, cheddar cheese, and all the toppings",
                            ImageUrl = "https://example.com/cheeseburger.jpg",
                            IsAvailable = true,
                            Name = "Cheeseburger",
                            Price = 10.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440021")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440034"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440012"),
                            Description = "Fresh romaine lettuce with parmesan and caesar dressing",
                            ImageUrl = "https://example.com/caesar-salad.jpg",
                            IsAvailable = true,
                            Name = "Caesar Salad",
                            Price = 8.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440020")
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440060"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 13, 43, 193, DateTimeKind.Utc).AddTicks(3565),
                            DeliveryAddress = "123 Main Street, Apt 4B, New York",
                            Status = "Pending",
                            TotalAmount = 27.98m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440061"),
                            CreatedAt = new DateTime(2026, 2, 14, 16, 13, 43, 193, DateTimeKind.Utc).AddTicks(4043),
                            DeliveryAddress = "123 Main Street, Apt 4B, New York",
                            Status = "Delivered",
                            TotalAmount = 20.98m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440070"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440030"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440060"),
                            Price = 12.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440071"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440031"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440060"),
                            Price = 14.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440072"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440032"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440061"),
                            Price = 9.99m,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440020"),
                            City = "New York",
                            ImageUrl = "https://example.com/pizza-palace.jpg",
                            RestaurantName = "Pizza Palace",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440002")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440021"),
                            City = "Los Angeles",
                            ImageUrl = "https://example.com/burger-king.jpg",
                            RestaurantName = "Burger King Local",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440004")
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 13, 43, 206, DateTimeKind.Utc).AddTicks(4547),
                            Email = "customer@example.com",
                            FullName = "John Customer",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 13, 43, 206, DateTimeKind.Utc).AddTicks(5007),
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 13, 43, 206, DateTimeKind.Utc).AddTicks(5010),
                            Email = "pizzapalace@example.com",
                            FullName = "Pizza Palace Owner",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440004"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 13, 43, 206, DateTimeKind.Utc).AddTicks(5012),
                            Email = "burgerking@example.com",
                            FullName = "Burger King Local Owner",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 13, 43, 206, DateTimeKind.Utc).AddTicks(5015),
                            Email = "courier@example.com",
                            FullName = "Fast Courier",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 3
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Customer", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("FastFoodApp.Core.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Food", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastFoodApp.Core.Entities.Supplier", "Supplier")
                        .WithMany("Foods")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Order", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastFoodApp.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Supplier", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("FastFoodApp.Core.Entities.Supplier", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Supplier", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
