// <auto-generated />
using System;
using FastFoodApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303062819_AddPaymentMethodToOrder")]
    partial class AddPaymentMethodToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastFoodApp.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440012"),
                            Name = "Salads"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440013"),
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440014"),
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440015"),
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440016"),
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440017"),
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440018"),
                            Name = "Soups"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440019"),
                            Name = "Sandwiches"
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440050"),
                            Address = "123 Main Street, Apt 4B",
                            City = "New York",
                            Phone = "+1-555-0100",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440051"),
                            Address = "456 Oak Avenue, Suite 200",
                            City = "Los Angeles",
                            Phone = "+1-555-0200",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440005")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440052"),
                            Address = "789 Pine Road, Building C",
                            City = "Chicago",
                            Phone = "+1-555-0300",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440006")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440053"),
                            Address = "321 Elm Street, Floor 5",
                            City = "Houston",
                            Phone = "+1-555-0400",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440008")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440054"),
                            Address = "654 Maple Drive, Unit 12",
                            City = "Phoenix",
                            Phone = "+1-555-0500",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440009")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440055"),
                            Address = "987 Cedar Lane, Apt 7",
                            City = "Philadelphia",
                            Phone = "+1-555-0600",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440005")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440056"),
                            Address = "135 Birch Way, Suite 101",
                            City = "San Antonio",
                            Phone = "+1-555-0700",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440006")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440057"),
                            Address = "246 Spruce Circle, #15",
                            City = "San Diego",
                            Phone = "+1-555-0800",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440008")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440058"),
                            Address = "357 Walnut Plaza, Unit 20",
                            City = "Dallas",
                            Phone = "+1-555-0900",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440009")
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440030"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Description = "Classic pizza with tomato sauce, mozzarella, and basil",
                            ImageUrl = "https://example.com/margherita.jpg",
                            IsAvailable = true,
                            Name = "Margherita Pizza",
                            Price = 12.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440020")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440031"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Description = "Pizza with tomato sauce, mozzarella, and pepperoni",
                            ImageUrl = "https://example.com/pepperoni.jpg",
                            IsAvailable = true,
                            Name = "Pepperoni Pizza",
                            Price = 14.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440020")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440032"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Description = "Juicy burger with beef patty, lettuce, tomato, and special sauce",
                            ImageUrl = "https://example.com/burger.jpg",
                            IsAvailable = true,
                            Name = "Classic Burger",
                            Price = 9.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440021")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440033"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Description = "Burger with beef patty, cheddar cheese, and all the toppings",
                            ImageUrl = "https://example.com/cheeseburger.jpg",
                            IsAvailable = true,
                            Name = "Cheeseburger",
                            Price = 10.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440021")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440034"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440012"),
                            Description = "Fresh romaine lettuce with parmesan and caesar dressing",
                            ImageUrl = "https://example.com/caesar-salad.jpg",
                            IsAvailable = true,
                            Name = "Caesar Salad",
                            Price = 8.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440020")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440035"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Description = "Juicy burger with beef patty, BBQ sauce, and crispy bacon",
                            ImageUrl = "https://example.com/bbq-burger.jpg",
                            IsAvailable = true,
                            Name = "BBQ Burger",
                            Price = 11.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440021")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440036"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Description = "Pizza with pineapple, ham, tomato sauce, and mozzarella",
                            ImageUrl = "https://example.com/hawaiian-pizza.jpg",
                            IsAvailable = true,
                            Name = "Hawaiian Pizza",
                            Price = 15.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440020")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440037"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440012"),
                            Description = "Fresh salad with feta cheese, olives, tomatoes, and cucumbers",
                            ImageUrl = "https://example.com/greek-salad.jpg",
                            IsAvailable = true,
                            Name = "Greek Salad",
                            Price = 9.49m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440021")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440038"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Description = "Two beef patties with double cheddar cheese and all the toppings",
                            ImageUrl = "https://example.com/double-cheeseburger.jpg",
                            IsAvailable = true,
                            Name = "Double Cheeseburger",
                            Price = 13.99m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440021")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440039"),
                            CategoryId = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Description = "Pizza loaded with fresh vegetables, tomato sauce, and mozzarella",
                            ImageUrl = "https://example.com/veggie-pizza.jpg",
                            IsAvailable = true,
                            Name = "Veggie Pizza",
                            Price = 13.49m,
                            SupplierId = new Guid("550e8400-e29b-41d4-a716-446655440020")
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440060"),
                            CreatedAt = new DateTime(2026, 3, 3, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(3754),
                            DeliveryAddress = "123 Main Street, Apt 4B, New York",
                            PaymentMethod = "",
                            Status = "Pending",
                            TotalAmount = 27.98m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440061"),
                            CreatedAt = new DateTime(2026, 3, 2, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(4147),
                            DeliveryAddress = "123 Main Street, Apt 4B, New York",
                            PaymentMethod = "",
                            Status = "Delivered",
                            TotalAmount = 20.98m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440062"),
                            CreatedAt = new DateTime(2026, 3, 3, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(4299),
                            DeliveryAddress = "456 Oak Avenue, Suite 200, Los Angeles",
                            PaymentMethod = "",
                            Status = "Pending",
                            TotalAmount = 34.97m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440005")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440063"),
                            CreatedAt = new DateTime(2026, 3, 1, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(4305),
                            DeliveryAddress = "789 Pine Road, Building C, Chicago",
                            PaymentMethod = "",
                            Status = "Delivered",
                            TotalAmount = 25.98m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440006")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440064"),
                            CreatedAt = new DateTime(2026, 3, 2, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(4314),
                            DeliveryAddress = "321 Elm Street, Floor 5, Houston",
                            PaymentMethod = "",
                            Status = "In Progress",
                            TotalAmount = 40.47m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440008")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440065"),
                            CreatedAt = new DateTime(2026, 2, 28, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(4320),
                            DeliveryAddress = "654 Maple Drive, Unit 12, Phoenix",
                            PaymentMethod = "",
                            Status = "Cancelled",
                            TotalAmount = 33.97m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440009")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440066"),
                            CreatedAt = new DateTime(2026, 2, 26, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(4324),
                            DeliveryAddress = "123 Main Street, Apt 4B, New York",
                            PaymentMethod = "",
                            Status = "Delivered",
                            TotalAmount = 22.98m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440067"),
                            CreatedAt = new DateTime(2026, 3, 2, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(4329),
                            DeliveryAddress = "456 Oak Avenue, Suite 200, Los Angeles",
                            PaymentMethod = "",
                            Status = "Pending",
                            TotalAmount = 29.98m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440005")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440068"),
                            CreatedAt = new DateTime(2026, 2, 27, 6, 28, 17, 290, DateTimeKind.Utc).AddTicks(4333),
                            DeliveryAddress = "789 Pine Road, Building C, Chicago",
                            PaymentMethod = "",
                            Status = "Delivered",
                            TotalAmount = 44.96m,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440006")
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440070"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440030"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440060"),
                            Price = 12.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440071"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440031"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440060"),
                            Price = 14.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440072"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440032"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440061"),
                            Price = 9.99m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440073"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440030"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440062"),
                            Price = 12.99m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440074"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440034"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440062"),
                            Price = 8.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440075"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440031"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440063"),
                            Price = 14.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440076"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440033"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440063"),
                            Price = 10.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440077"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440032"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440064"),
                            Price = 9.99m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440078"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440034"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440064"),
                            Price = 8.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440079"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440030"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440065"),
                            Price = 12.99m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440080"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440033"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440066"),
                            Price = 10.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440081"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440034"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440066"),
                            Price = 8.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440082"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440031"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440067"),
                            Price = 14.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440083"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440032"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440067"),
                            Price = 9.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440084"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440030"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440068"),
                            Price = 12.99m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440085"),
                            FoodId = new Guid("550e8400-e29b-41d4-a716-446655440031"),
                            OrderId = new Guid("550e8400-e29b-41d4-a716-446655440068"),
                            Price = 14.99m,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440020"),
                            City = "New York",
                            ImageUrl = "https://example.com/pizza-palace.jpg",
                            RestaurantName = "Pizza Palace",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440002")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440021"),
                            City = "Los Angeles",
                            ImageUrl = "https://example.com/burger-king.jpg",
                            RestaurantName = "Burger King Local",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440004")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440022"),
                            City = "Chicago",
                            ImageUrl = "https://example.com/taco-fiesta.jpg",
                            RestaurantName = "Taco Fiesta",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440005")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440023"),
                            City = "Houston",
                            ImageUrl = "https://example.com/sushi-paradise.jpg",
                            RestaurantName = "Sushi Paradise",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440006")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440024"),
                            City = "Phoenix",
                            ImageUrl = "https://example.com/pasta-house.jpg",
                            RestaurantName = "Pasta House",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440007")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440025"),
                            City = "Philadelphia",
                            ImageUrl = "https://example.com/bbq-smokehouse.jpg",
                            RestaurantName = "BBQ Smokehouse",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440008")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440026"),
                            City = "San Antonio",
                            ImageUrl = "https://example.com/thai-kitchen.jpg",
                            RestaurantName = "Thai Kitchen",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440009")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440027"),
                            City = "San Diego",
                            ImageUrl = "https://example.com/greek-taverna.jpg",
                            RestaurantName = "Greek Taverna",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440005")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440028"),
                            City = "Dallas",
                            ImageUrl = "https://example.com/kebab-express.jpg",
                            RestaurantName = "Kebab Express",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440006")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440029"),
                            City = "Austin",
                            ImageUrl = "https://example.com/vegan-delights.jpg",
                            RestaurantName = "Vegan Delights",
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440008")
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            CreatedAt = new DateTime(2026, 3, 3, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(5698),
                            Email = "customer@example.com",
                            FullName = "John Customer",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            CreatedAt = new DateTime(2026, 3, 3, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6163),
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            CreatedAt = new DateTime(2026, 3, 3, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6170),
                            Email = "pizzapalace@example.com",
                            FullName = "Pizza Palace Owner",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440004"),
                            CreatedAt = new DateTime(2026, 3, 3, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6172),
                            Email = "burgerking@example.com",
                            FullName = "Burger King Local Owner",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            CreatedAt = new DateTime(2026, 3, 3, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6175),
                            Email = "courier@example.com",
                            FullName = "Fast Courier",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            CreatedAt = new DateTime(2026, 2, 21, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6193),
                            Email = "sarah.johnson@example.com",
                            FullName = "Sarah Johnson",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440006"),
                            CreatedAt = new DateTime(2026, 2, 23, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6209),
                            Email = "michael.smith@example.com",
                            FullName = "Michael Smith",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440007"),
                            CreatedAt = new DateTime(2026, 2, 26, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6215),
                            Email = "emily.davis@example.com",
                            FullName = "Emily Davis",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440008"),
                            CreatedAt = new DateTime(2026, 2, 28, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6221),
                            Email = "robert.wilson@example.com",
                            FullName = "Robert Wilson",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440009"),
                            CreatedAt = new DateTime(2026, 3, 2, 6, 28, 17, 314, DateTimeKind.Utc).AddTicks(6226),
                            Email = "jessica.martinez@example.com",
                            FullName = "Jessica Martinez",
                            PasswordHash = "$2a$11$4e1jY8Zzv4vYf6gblK4gWe8r7q3K2m9Zc8x5V3k1q2w3e4r5t6y7u8i9o0p",
                            Role = 1
                        });
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Customer", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("FastFoodApp.Core.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Food", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastFoodApp.Core.Entities.Supplier", "Supplier")
                        .WithMany("Foods")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Order", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastFoodApp.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Supplier", b =>
                {
                    b.HasOne("FastFoodApp.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("FastFoodApp.Core.Entities.Supplier", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.Supplier", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("FastFoodApp.Core.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
